zooniverse/ci-cd

.github/workflows/deploy_static.yaml, .github/workflows/npm_build.yaml
Adds npm_build.yaml and deploy_static.yaml, reusable workflows for building, storing, and deploying npm-built static sites. This process was modeled on PFE, where the result of `npm build` is stored as an artifact, which is then picked up by the deploy workflow and pushed out via `az` to blob storage. I believe this means the context of a given artifact is the action itself, so there won't be collisions.
These should work for PFE (that's the point here), but I'm planning on test on data.galaxyzoo.org. That's kind of an older site, but it uses npm and needs to deploy to blob storage just like everything else.
=> Add static site build and deploy workflows

.github/workflows/deploy_static.yaml
Add optional input to blob storage deployments to set the max-age of all files not called index.html (which stays at 60s).
=> Use an input with a default for max-age non-index files

.github/workflows/npm_build.yaml
Upgrade to `actions/setup-node@v2`, which includes npm package caching. Remove the separate caching step.
=> Upgrade to actions/setup-node@v2

.github/workflows/run_rspec.yaml
A Rails repo might not include a no-focus script, but that check should still be run when running the tests. Since it's just one line, put it in the shared spec runner.
=> Use one-line no-focus check, not a script, for rspec running

.github/workflows/db_migration.yaml, README.md
Prevent a race condition where the "push to master" event fires both the DB Migration and Deploy to Staging workflows at the same time. The Deploy workflow builds and pushes the new image to GHCR, then deploys that image to Kubernetes. Currently, the Migration job uses the Run Task method of determining the currently deployed tag from the k8s pod, then instantiates a new pod based on that image to run the job. However, this will be the old, previously-deployed commit if the deploy job doesn't finish first, which it probably won't.
Now, the same commit id being used to build and push the new image is also passed to the Migration job and used to create the job pod. It's possible that this still doesn't fly because the image with that tag doesn't exist in GHCR until the Deploy job is done. …
=> Use SHA instead of deployed image tag for DB migrations

.github/workflows/build_and_push_image.yml
Takes a repo name and a commit hash. Used for building/pushing images on PR updates and other common events.
=> Add Action: Build and Push Image

.github/workflows/deploy_static.yaml
New `az` client version 2.34.0 introduced a breaking change wherein the previous default of "overwrite" was changed to "throw an error instead of overwrite if the new --overwrite flag is not included".
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli#storage
This overwrite-by-default behavior was expected by this action, and so now specifies the `--overwrite` flag explicitly.
=> Add newly-required --overwrite flag to az uploads

.github/workflows/deploy_static.yaml
The azure/CLI action by default uses the `latest` version of the Azure CLI. This is currently not actually happening, as the action pulled 2.33.1, then for a few hours yesterday used 2.34.1, then reverted back to 2.33.1, where it sits right now.
This pins the version to 2.33.1 so that when the update is pushed out again, all our uploads won't fail. The upload tester will run as a check on this PR, and when that update does come, we should be able to use that test workflow to safely update and test our deploy_static workflow prior to making it live for our other sites.
=> Pin az CLI version to 2.33.1

.github/workflows/deploy_app.yaml
Some apps don't use the standard deployment naming scheme of `app-name-environment`, such as aggregation. For these, just allowing the "deploy necessary?" check to be skipped allows the shared deploy_app workflow to be reused without changing the k8s template contents.
=> Allow deploy check to be skipped in deploy_app workflow

.github/workflows/build_and_push_image.yaml
Not required, and defaults to an empty string if not provided.
=> Allow optional inclusion of --build-args to Docker

.github/workflows/deploy_static.yaml
Static deploys should only deploy the downloaded build, not the entire source code and Git history.
Closes #23.
=> Remove checkout from static deploys

.github/workflows/build_and_push_image.yaml
Based on https://github.com/docker/build-push-action#inputs
This PR adds the ability to specify the dockerfile as an input to the build and push action. It preserves the default value of `Dockerfile` for backwards compatibility with the action
=> add dockerfile input variable

.github/workflows/deploy_static.yaml
Dependabot version of this doesn't seem to inherit the permissions required to run the tests. Opening this myself to test the tests.
=> Update download-artifact to v3

.github/workflows/npm_build.yaml
`actions/setup-node@v2` is generating deprecation warnings so this upgrades to v3.
=> Update NPM builds to latest setup-node

.github/workflows/build_and_push_image.yaml, .github/workflows/deploy_app.yaml
Testing the hypothesis that some tests are failing due to @dependabot not having the necessary permissions to push to GHCR. This is probably good practice, so if it turns out to be true there may be some tweaking necessary to run tests without that bit.
=> Update docker login-action to v2

.github/workflows/build_and_push_image.yaml
GHA is deprecating the `set-output` syntax I used to tag docker images. This updates to the new environment var syntax.
=> Update deprecated set-output syntax

.github/workflows/build_and_push_image.yaml, .github/workflows/db_migration.yaml, .github/workflows/deploy_app.yaml, .github/workflows/npm_build.yaml, .github/workflows/run_rspec.yaml, .github/workflows/run_task.yaml
Same as https://github.com/zooniverse/ci-cd/pull/56.
Actions that run as a result of Dependabot opening a PR do not have access to GITHUB_TOKEN in those actions. Need a less cumbersome way to allow Dependabot PRs to go through CI/CD checks without manually checking out/renaming/`git push --set-upstream origin`ing each of them. TBD.
Bumps [actions/checkout](https://github.com/actions/checkout) from 3.3.0 to 3.5.2.
- [Release notes](https://github.com/actions/checkout/releases)
- [Changelog](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/checkout/compare/v3.3.0...v3.5.2)
---
updated-dependencies:
- dependency-name: actions/checkout dependency-type: direct:production update-type: version-update:semver-minor ...
=> Bump actions/checkout from 3.3.0 to 3.5.2

.github/workflows/npm_build.yaml
Node 14 is End-Of-Life in April 2023. Node 16 became a maintenance release in October 2022 and support ends in September 2023. This PR bumps the default NodeJS to 18 (`lts/hydrogen`),  which is supported until April 2025.
=> Bump default NodeJS to 18 LTS

.github/workflows/deploy_app.yaml, README.md
https://github.com/zooniverse/ci-cd/pull/44 is right, `repo_name` is never actually used in that action. Removing it from the list of arguments would cause all repos that currently send it to fail, so I'll make it optional and remove it from repos when possible.
Also adds sending build-args to the build/push workflow to the example in the README.
=> Make repo_name optional in deploy_app workflow

.github/workflows/npm_build.yaml
Related to https://github.com/zooniverse/ci-cd/pull/33#issuecomment-1268040406
Run `npm ci` system with `--ignore-scripts` to secure the npm builds from package supply chain attacks via shell access in pre / post scripts. See https://docs.npmjs.com/cli/v7/commands/npm-install#ignore-scripts
=> add --ignore-scripts to npm build

.github/workflows/build_and_push_image.yaml, .github/workflows/db_migration.yaml, .github/workflows/deploy_app.yaml, .github/workflows/npm_build.yaml, .github/workflows/run_rspec.yaml, .github/workflows/run_task.yaml
Updates `actions/checkout`, and `docker/[build-push-image|action-login|setup-buildx-action]` in relevant actions.
The Dependabot PR for `actions/checkout@v4` kept failing the image push part of the tests with a github-side 503. The tests run fine on main, though, which is wild because there's no interface change afaik. Maybe updating these action versions at once (incl the apparently offending `build-push-action` will shake it loose. They all need it, anyway.
=> Update shared action versions

.github/workflows/build_and_push_image.yaml
Version 6 is still kind of new, want to make sure these tests pass.
=> Update docker-build-push to v6

.github/workflows/deploy_app.yaml
Allow docker-login to update to 3.3.0, up to <4.
=> Use more permissive login-action version

.github/workflows/purge_cache.yaml, .github/workflows/test_cache_purge.yaml, README.md
Inputs are strings: the name of the Front Door (e.g. `www-zooniverse-org`) and the content path to purge (e.g. `/`, `/about/`, `/about/*`, etc). 
This starts with support for a single string and requires multiple calls to purge multiple paths. However, it is possible to pass a string that can be processed into a matrix strategy (like `"'/', '/*'"` or `"'/', '/about', '/get-involved'"`). I'm thinking that right now we might just process `'/*'` for the initial use case for this (post-FEM deploys) so I'll revisit if required.
Also includes a test that purges the cache for https://frontend.preview.zooniverse.org/assets/star.jpg
=> Add Purge Front Door Cache action

.github/workflows/delete_blobs.yaml
Adds a new shared action to delete blobs from the `$web` container of the zooniversestatic storage account. PFE branch deploys just accumulated and were never cleaned up. This provides a means for staging deploys to clean up the associated branch deploy. The PFE staging deploy action will be amended to include running this action with the target of `preview.zooniverse.org/panoptes-front-end/pr-xxxx`. 
This includes the `--dryrun` flag to start with. The contents of the target blob won't be deleted but will be logged so that I can ensure that the path inputs to this action are correct. I'll remove the flag in a new PR.
=> Add delete web blobs action

.github/workflows/deploy_static.yaml
Azure CLI version in their GHA was pinned a long time ago in order to avoid some issues on their end. This should be solved and so we can use the latest az cli version. Also, the default upload behavior post-2.33 is different and now requires the `--overwrite` flag to be included.
Also in the deploy_static action, the max_age input should be a string as noted.
=> Unpin az cli version
